##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-themes
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - pkg-config

before_scripts:
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - mkdir html-report
  - ./autogen.sh
  - make

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-themes-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 3.22.0
    notify_servers:
      - https://release.cafe-desktop.org/release

