##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/cafe-themes
    - gcc
    - git
    - make
    - gtk2
    - intltool
    - cafe-common
    - which

  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-themes
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - cafe-common
    - pkg-config

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/cafe-themes.git
    - gcc
    - gdk-pixbuf2-devel
    - git
    - gtk2-devel
    - make
    - cafe-common
    - redhat-rpm-config

  ubuntu:
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - cafe-common
    - pkg-config

variables:
  - CFLAGS="-Wall -Werror=format-security"

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-themes-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 3.22.0
    notify_servers:
      - https://release.cafe-desktop.org/release

