##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # cafe B-D: cafe-common
    - aptitude
    - clang
    - clang-tools
    - expect #required for unbuffer
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - pkg-config

before_scripts:
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - ./make-scanbuild
  - ./exit-warning
