##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/cafe-themes
    - autoconf
    - automake
    - gcc
    - git
    - gtk2
    - intltool
    - make
    - pkgconf
    - which

  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-themes
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - pkg-config

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/cafe-themes.git
    - autoconf
    - automake
    - gcc
    - gdk-pixbuf2-devel
    - gettext-devel
    - git
    - gtk2-devel
    - make
    - redhat-rpm-config
    - which
    - xz

  ubuntu:
    - git
    - icon-naming-utils
    - intltool
    - libgtk2.0-dev
    - libxml-parser-perl
    - make
    - pkg-config

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  # Install cafe-common from master branch
  - if [ ! -e cafe-common-master ]; then
  -     cd ${START_DIR}
  -     git clone --depth 1  https://github.com/cafe-desktop/cafe-common.git -b master cafe-common-master
  -     cd cafe-common-master
  -     ./autogen.sh
  -     if [ ${DISTRO_NAME} == "debian" -o ${DISTRO_NAME} == "ubuntu" ];then
  -         ./configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu
  -     else
  -         ./configure --prefix=/usr
  -     fi
  -     make
  -     make install
  - fi

build_scripts:
  - mkdir html-report
  - ./autogen.sh
  - make

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: cafe-themes-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 3.22.0
    notify_servers:
      - https://release.cafe-desktop.org/release

