##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./testrepo
